### ISSUE TITLE
Link zu DB UX Design System ist broken

### ISSUE THREAD

**Issue by DanielGlaas** [db-ui/.github#1]
Hallo,
in der Readme.md gibt es einen Link zu [DB UX Design System](https://marketingportal.extranet.deutschebahn.com/marketingportal/Design-Anwendungen/DB-UX-Design-System/Design-fuer-Apps-Web/UI-Komponenten), allerdings gibt es diese Seite nicht mehr:
![image](https://github.com/user-attachments/assets/60dd31f4-2e5a-44a7-98d1-93b314091c7c)

**Comment by mfranzke** [comment]
> Hallo, in der Readme.md gibt es einen Link zu [DB UX Design System](https://marketingportal.extranet.deutschebahn.com/marketingportal/Design-Anwendungen/DB-UX-Design-System/Design-fuer-Apps-Web/UI-Komponenten), allerdings gibt es diese Seite nicht mehr: ![image](https://private-user-images.githubusercontent.com/58786395/372067140-60dd31f4-2e5a-44a7-98d1-93b314091c7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2OTY0OTEsIm5iZiI6MTcyNzY5NjE5MSwicGF0aCI6Ii81ODc4NjM5NS8zNzIwNjcxNDAtNjBkZDMxZjQtMmU1YS00NGE3LTk4ZDEtOTNiMzE0MDkxYzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDExMzYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3ZDlmNjM1ZjBmMzg4ZDViNTNlNmQwN2MyNTk2NjQ4ODdiNjk1MmY4MGNhMDExMmMxZDU5Zjg3Mzc0M2FhNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3xOuK-LscO6lZY0ISb5YfzbHtYUGK4POrR64klriinA)

danke Dir, good catch !
